# Generated by Django 4.2.16 on 2024-12-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0189_alter_profile_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ('order',), 'permissions': (('view_all_contest_problem', 'View all contest problem'),), 'verbose_name': 'contest problem', 'verbose_name_plural': 'contest problems'},
        ),
    ]
