# Generated by Django 4.2.16 on 2025-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0190_alter_contestproblem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='typo_contest',
        ),
    ]
