name: build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install flake8
      run: pip install flake8 flake8-import-order flake8-future-import flake8-commas flake8-logging-format
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('requirements.txt') }}
    - name: Install unit test dependencies
      run: |
        pip install wheel
        pip install -r requirements.txt
        pip install mysqlclient coverage
        cp .ci.settings.py tmath/local_settings.py
    - name: Start MySQL
      run: sudo systemctl start mysql.service
    - name: Run unit tests
      run: coverage run --source=. manage.py test judge
    - name: Generate coverage report
      run: coverage xml
    - uses: codecov/codecov-action@v3
  styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 19
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install npm packages
        run: | 
          npm install -D tailwindcss
          npm install -D @tailwindcss/forms
          npm install -D @tailwindcss/typography

      - name: Build style.css
        run: npx tailwindcss -i resources/main.css -o resources/full_style.css
